package View;

import Controller.ControllerFormCadastroImpressora;
import DAO.Conexao;
import DAO.TipoImpressaoDAO;
import Model.TipoImpressao;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;

public class FormCadastroImpressao extends javax.swing.JFrame {

    private final ControllerFormCadastroImpressora controller;
    
    public FormCadastroImpressao() throws SQLException {
        initComponents();
        this.controller = new ControllerFormCadastroImpressora(this);
        iniciar();
        setTitle("Registro de Impressão");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLimparTela = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtfldValor = new javax.swing.JTextField();
        spnrQtdeFolhas = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbbxTipoImpressao = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemRelatorio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimparTela.setText("Limpar tela");
        btnLimparTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparTelaActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimparTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 150, -1));

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 210, 90));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));
        getContentPane().add(txtfldValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 280, 30));

        spnrQtdeFolhas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnrQtdeFolhasStateChanged(evt);
            }
        });
        getContentPane().add(spnrQtdeFolhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 80, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quantidade de folhas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo de impressão");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        cmbbxTipoImpressao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbbxTipoImpressaoItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbbxTipoImpressao, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 293, 41));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/FundoTelaCadastro.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Opções");

        MenuItemRelatorio.setText("Relatório de Vendas");
        MenuItemRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemRelatorioActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemRelatorio);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            this.controller.registrarVenda();
        } catch (SQLException ex) {
            Logger.getLogger(FormCadastroImpressao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cmbbxTipoImpressaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbbxTipoImpressaoItemStateChanged
        this.controller.atualizaValor();
    }//GEN-LAST:event_cmbbxTipoImpressaoItemStateChanged

    private void spnrQtdeFolhasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnrQtdeFolhasStateChanged
        this.controller.atualizaValor();
        
    }//GEN-LAST:event_spnrQtdeFolhasStateChanged

    private void btnLimparTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparTelaActionPerformed
        this.controller.limparTela();
    }//GEN-LAST:event_btnLimparTelaActionPerformed

    private void MenuItemRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemRelatorioActionPerformed
        try {
            this.controller.entrarTelaRelatorio();
        } catch (SQLException ex) {
            Logger.getLogger(FormCadastroImpressao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MenuItemRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroImpressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroImpressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroImpressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroImpressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormCadastroImpressao().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormCadastroImpressao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public JComboBox<String> getCmbbxTipoImpressao() {
        return cmbbxTipoImpressao;
    }

    public void setCmbbxTipoImpressao(JComboBox<String> cmbbxTipoImpressao) {
        this.cmbbxTipoImpressao = cmbbxTipoImpressao;
    }

    public JSpinner getSpnrQtdeFolhas() {
        return spnrQtdeFolhas;
    }

    public void setSpnrQtdeFolhas(JSpinner spnrQtdeFolhas) {
        this.spnrQtdeFolhas = spnrQtdeFolhas;
    }

    public JTextField getTxtfldValor() {
        return txtfldValor;
    }

    public void setTxtfldValor(JTextField txtfldValor) {
        this.txtfldValor = txtfldValor;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemRelatorio;
    private javax.swing.JButton btnLimparTela;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbbxTipoImpressao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSpinner spnrQtdeFolhas;
    private javax.swing.JTextField txtfldValor;
    // End of variables declaration//GEN-END:variables

    private void iniciar() throws SQLException {
        this.controller.atualizaTipoImpressao();
        this.controller.atualizaValor();
    }

  
}
